openfusion_ros:
  openfusion_ros:
    ros__parameters:
      robot:
        parent_frame: "map"
        child_frame: "carter_camera_stereo_right"
        pose_topic: "robot_pose"
        max_delta_time: 0.2
        camera:
          rgb_topic: "/rgb"
          depth_topic: "/depth"
          debug_images: false
          max_buffer_size: 50
          max_buffer_age_sec: 3.0
      append_poses_frequency: 10.0
      pointcloud_frequency: 1.0
      pose_min_translation: 0.05
      pose_min_rotation: 5.0
      topk: 20
      depth_max: 10.0
      use_sim_time: true
      skip_loading_model: false
      min_inferno_score: 0.2
      max_inferno_score: 0.45

cloud_cluster_node:
  ros__parameters:
    publish_frequency: 10.0  # Hz
    cluster_tolerance: 0.15 # cm
    min_cluster_size: 100
    max_cluster_size: 25000
    voxel_leaf_size: 0.03  # reduce voxel size (cm), for better performance
    frame_id: "map"  # refrence frame for node graph
    semantic_pointcloud_topic: "/openfusion_ros/semantic_pointcloud_xyzi"  # topic for point cloud data